### ISSUE TITLE
这个lsm树还考虑优化吗

### ISSUE THREAD

**Issue by fy1214** [whuanle/lsm#5]
大佬的项目还考虑后续优化吗？目前我在这基础上加了LRU的cache，memtable加了跳表选项，后续还想对compaction进行优化，因为写放大有点严重

**Comment by whuanle** [comment]
个人精力有限，暂时不会往专业方向发展。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月20日(周六) 晚上9:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [whuanle/lsm] 这个lsm树还考虑优化吗 (Issue #5)




 
大佬的项目还考虑后续优化吗？目前我在这基础上加了LRU的cache，memtable加了跳表选项，后续还想对compaction进行优化，因为写放大有点严重

**Comment by kebukeYi** [comment]
> 

能看看你的改进优化吗？

**Comment by whuanle** [comment]
@fy1214 如果要优化的化，似乎不应该放在我的私人仓库里面了。
应该改个名字，然后大家一起完成，做成好一些的项目。

**Comment by hello-ikun** [comment]
让我学习学习 感觉是一个不错的项目呢！
