### ISSUE TITLE
当内存表持久化为SSTable时，并没有同步控制 wal.log 文件

### ISSUE THREAD

**Issue by kebukeYi** [whuanle/lsm#6]
在 `Check.go` 文件中的 #checkMemory() {} 方法中，在将 `MemoryTree`进行交换创建新`MemoryTree`  时，此时的 wal 中可能是含有新的`MemoryTree` 中的一些数据(新插入的数据)，那么在将旧`MemoryTree` 持久化完毕后，就直接删除 wal 文件的做法是否不妥？因为此时的 wal 文件中是含有新数据的，直接删除的话，尽管新`MemoryTree`中也含有新数据，但是假如之后宕机了，那么新数据就 无法 进行恢复了，因此造成数据丢失。

**Comment by whuanle** [comment]
目前观测是有 Bug。
这可啥整

**Comment by kebukeYi** [comment]
1. 将 wal 和 内存有序Tree结构 两者 共同绑定在 MemTable 这个结构中, 并新增  imemTables[] 数组结构;
因为当前的设计是 wal 是单独分开 并 只有一个 ,  但是 memTable 是可能存在两个 (可写 和 仅可读), 因此会出现数据不一致情况;
2. 在进行set()时, 假如当前 memTable大小 达到阈值, 那就将当前 memTable 设置为 imemTable, 并将其添加在 imemTables[] 中;
同时新建一个 memTable(wal和tree) , 这样 tree 和 wal 就能 对应 绑定 , 同时新增  , 同时被删除 , 不会出现数据不一致现象;
3. 合并逻辑, 差不多, 就是监听  imemTables[] 数组结构 , 进行循环取出元素, 进行刷盘 ,最后加锁 删除imemTable元素,删除wal;
![image](https://github.com/whuanle/lsm/assets/43784129/14b36382-9514-4c88-8315-aea1394bc223)

**Comment by klboke** [comment]
楼上是不是看过 RocksDB 的实现

**Comment by kebukeYi** [comment]
没看 RocksDB的实现源码，只是看了一些 基于 LSM 结构 的 GO 语言开源的 KV 项目代码，比如 roseDB  badger 等一些项目；

**Comment by whuanle** [comment]
https://github.com/whuanle/lsm/pull/8
感谢网友的修复
