### ISSUE TITLE
在数据库compress关闭数据库可能会导致不能正常重启

### ISSUE THREAD

**Issue by huiming23344** [whuanle/lsm#7]
在触发compress时并写入新的kv值时，关闭数据库后有几率不能正常打开，检查发现数据文件夹中的0.0.db文件为空，判断为在写入SStable文件时被关闭，同时wal文件并没有被清空，所以理论上系统是应该可以被正常重启的
```go
	lsm.Start(config.Config{
		DataDir:       "./data",
		Level0Size:    100,
		PartSize:      4,
		Threshold:     9,
		CheckInterval: 2,
	})
	insertValuesByCount(10, 10)
	time.Sleep(2 * time.Second)
	insertValuesByCount(6, 0)
```
重启后提示：
```
2024/08/05 20:38:40 Loading a Configuration File
2024/08/05 20:38:40 Initializing the database
2024/08/05 20:38:40 Loading wal.log...
2024/08/05 20:38:40 Loaded wal.log,Consumption of time :  593.75µs
2024/08/05 20:38:40 Loading database...
2024/08/05 20:38:40 The SSTable list are being loaded
2024/08/05 20:38:40 Loading the  data/0.0.db
2024/08/05 20:38:40 Error reading metadata  data/0.0.db
2024/08/05 20:38:40 Loading the  data/0.0.db ,Consumption of time :  274.625µs
2024/08/05 20:38:40 The SSTable list are being loaded,consumption of time :  899.459µs
seek data/0.0.db: invalid argument
```
解决方案：
- 尝试给数据库加入close方法安全关闭？
- 检查了一下，应该是在`initload.go`中`(table *SSTable) loadMetaInfo()`函数读取`.db'文件为空的时候发生的报错，可否给一这这个函数加入判断，若文件为空直接忽略文件？因为异常关闭时，wal中的记录其实是没有被删除的，这里忽略也应该可以正常初始化数据库，保证数据不丢失

**Comment by whuanle** [comment]
😃要不来个 PR，最近太忙了，都没时间搞这个。



---原始邮件---
发件人: "Luo ***@***.***&gt;
发送时间: 2024年8月5日(周一) 晚上9:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [whuanle/lsm] 在数据库compress关闭数据库可能会导致不能正常重启 (Issue #7)




 
在触发compress时并写入新的kv值时，关闭数据库后有几率不能正常打开，检查发现数据文件夹中的0.0.db文件为空，判断为在写入SStable文件时被关闭，同时wal文件并没有被清空，所以理论上系统是应该可以被正常重启的
 	lsm.Start(config.Config{ 		DataDir:       "./data", 		Level0Size:    100, 		PartSize:      4, 		Threshold:     9, 		CheckInterval: 2, 	}) 	insertValuesByCount(10, 10) 	time.Sleep(2 * time.Second) 	insertValuesByCount(6, 0)
 
重启后提示：
 2024/08/05 20:38:40 Loading a Configuration File 2024/08/05 20:38:40 Initializing the database 2024/08/05 20:38:40 Loading wal.log... 2024/08/05 20:38:40 Loaded wal.log,Consumption of time :  593.75µs 2024/08/05 20:38:40 Loading database... 2024/08/05 20:38:40 The SSTable list are being loaded 2024/08/05 20:38:40 Loading the  data/0.0.db 2024/08/05 20:38:40 Error reading metadata  data/0.0.db 2024/08/05 20:38:40 Loading the  data/0.0.db ,Consumption of time :  274.625µs 2024/08/05 20:38:40 The SSTable list are being loaded,consumption of time :  899.459µs seek data/0.0.db: invalid argument  
解决方案：
  
尝试给数据库加入close方法安全关闭？
 
检查了一下，应该是在initload.go中(table *SSTable) loadMetaInfo()函数读取`.db'文件为空的时候发生的报错，可否给一这这个函数加入判断，若文件为空直接忽略文件？因为异常关闭时，wal中的记录其实是没有被删除的，这里忽略也应该可以正常初始化数据库，保证数据不丢失

**Comment by whuanle** [comment]
感谢修复
https://github.com/whuanle/lsm/pull/8
